# config/config.yaml
ai:
  model_type: "transformer"
  embedding_dim: 256
  num_heads: 8
  num_layers: 6

data:
  train_data_path: "data/raw/train_poems.txt"
  test_data_path: "data/raw/test_poems.txt"

web:
  host: "0.0.0.0"
  port: 5000

x_automation:
  default_posting_interval: 3600
  max_retries: 3

# config/secrets.yaml
x_api:
  api_key: "your_api_key_here"
  api_secret: "your_api_secret_here"
